#version: "3.7"
#
## Services
#services:
#
#  redis:
#    image: redis:latest
#    restart: always
#    ports:
#      - "6379:6379"
#    volumes:
#      - redis_data:/data
#
#  redis_insight:
#    image: redislabs/redisinsight:latest
#    restart: always
#    ports:
#      - "8009:8009"
#    volumes:
#      - redis_insight_data:/db
#
#volumes:
#  redis_data:
#  redis_insight_data: