services:
  redis:
    image: redislabs/redismod
    container_name: redis
    ports:
      - 6379:6379
    user: redis

    networks:
      - redisnet
  redisinsight:
    image: redislabs/redisinsight:1.13.0
    ports:
      - '8001:8001'
    volumes:
      - redisinsight_db:/db
    networks:
      - redisnet

volumes:
  redisinsight_db:


networks:
  redisnet: